files:
  - source: /translations/en.json
    translation: /translations/%two_letters_code%.json
    update_option: update_as_unapproved
  - source: /ios/Seek/en.lproj/InfoPlist.strings
    translation: /ios/Seek/%osx_code%/InfoPlist.strings
    update_option: update_as_unapproved
  - source: /fastlane/metadata/android/en/full_description.txt
    translation: /fastlane/metadata/android/%two_letters_code%/full_description.txt
    update_option: update_as_unapproved
  - source: /fastlane/metadata/android/en/short_description.txt
    translation: /fastlane/metadata/android/%two_letters_code%/short_description.txt
    update_option: update_as_unapproved
  - source: /fastlane/metadata/android/en/title.txt
    translation: /fastlane/metadata/android/%two_letters_code%/title.txt
    update_option: update_as_unapproved
  - source: /fastlane/metadata/en/description.txt
    translation: /fastlane/metadata/%two_letters_code%/description.txt
    update_option: update_as_unapproved
  - source: /fastlane/metadata/en/keywords.txt
    translation: /fastlane/metadata/%two_letters_code%/keywords.txt
    update_option: update_as_unapproved
  - source: /fastlane/metadata/en/name.txt
    translation: /fastlane/metadata/%two_letters_code%/name.txt
    update_option: update_as_unapproved
  - source: /fastlane/metadata/en/subtitle.txt
    translation: /fastlane/metadata/%two_letters_code%/subtitle.txt
    update_option: update_as_unapproved
